"""initial tables

Revision ID: 7b2d739be06b
Revises: 
Create Date: 2026-01-18 20:44:14.344533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b2d739be06b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('favorites', sa.Column('device_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_favorites_device_id'), 'favorites', ['device_id'], unique=False)
    op.drop_column('favorites', 'created_at')
    op.drop_column('favorites', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_favorites_device_id'), table_name='favorites')
    op.drop_column('favorites', 'device_id')
    op.alter_column('cars', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
