"""Add public_id to car_images

Revision ID: ac0d00fef03e
Revises: e9e2ae484cc8
Create Date: 2026-01-21 05:16:10.729094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0d00fef03e'
down_revision: Union[str, None] = 'e9e2ae484cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_images', sa.Column('public_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_images', 'public_id')
    # ### end Alembic commands ###
