"""vile

Revision ID: e9e2ae484cc8
Revises: 7b2d739be06b
Create Date: 2026-01-21 05:12:14.638289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e2ae484cc8'
down_revision: Union[str, None] = '7b2d739be06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_images', sa.Column('public_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_images', 'public_id')
    # ### end Alembic commands ###
