"""Alembic environment script for handling migrations.

This file is auto-generated by Alembic, but we've customized it to use the
DATABASE_URL environment variable (e.g., from Render) for the database connection.
It falls back to the alembic.ini config if DATABASE_URL is not set (useful for local dev).

Key Changes:
- Overrides the SQLAlchemy URL with DATABASE_URL in run_migrations_online().
- Converts 'postgres://' to 'postgresql://' for SQLAlchemy/psycopg2 compatibility.
- Assumes your models are in app.models (adjust the 'import models' line if needed).

Place this in your /alembic/env.py file, commit, and push to trigger a new deploy.
"""

import os
import sys
from logging.config import fileConfig
from sqlalchemy import engine_from_config, pool
from alembic import context

# This is the Alembic Config object, which provides access to
# alembic.ini settings. Called by alembic.command.
config = context.config

# Interpret the config file for Python logging. This line sets up loggers
# for the whole application at runtime, not just for Alembic.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Add your model's MetaData object here for 'autogenerate' support.
# from myapp import models  # Adjust to your app's models import
from app.models import Base  # Example: Assuming your models use a Base class
target_metadata = Base.metadata

# Custom function to get the SQLAlchemy URL from env var
def get_url():
    url = os.getenv("DATABASE_URL")
    if url:
        # Render/others use 'postgres://', but SQLAlchemy + psycopg2 prefers 'postgresql://'
        if url.startswith("postgres://"):
            url = url.replace("postgres://", "postgresql://", 1)
        return url
    # Fallback to alembic.ini (for local dev)
    return config.get_main_option("sqlalchemy.url")

# Run migrations in 'online' mode (with a real DB connection).
def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    # Override the config's sqlalchemy.url with our env var
    config.set_main_option("sqlalchemy.url", get_url())
    
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()

# Run migrations in 'offline' mode (inspect DB without connecting).
def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = get_url()  # Use same URL logic
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()

# Determine if we're running online or offline.
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
